### ISSUE TITLE
Nazwiska dwuczłonowe

### ISSUE THREAD

**Issue by KacperCe** [RybarskiDominik/GML-2021#13]
Program nie rozpoznaje nazwisk dwuczłonowych

![image](https://github.com/RybarskiDominik/GML-2021/assets/41371367/7cf2950e-103c-43e1-ad80-9f40c19e449c)
![image](https://github.com/RybarskiDominik/GML-2021/assets/41371367/787686c9-7b77-4eff-bf9e-ce4973e0e9bb)

**Comment by RybarskiDominik** [comment]
Poprawione.
https://github.com/RybarskiDominik/GML-2021/releases
