### ISSUE TITLE
Niewyświetlanie numeru lokalu

### ISSUE THREAD

**Issue by KacperCe** [RybarskiDominik/GML-2021#14]
Program nie dodaje do pola adres numeru lokalu
![image](https://github.com/user-attachments/assets/3daf01dc-d240-42e4-8b95-737ca2c126b1)
![image](https://github.com/user-attachments/assets/b8a7bc03-4bb0-4608-b22e-0c35bc79d3be)

**Comment by RybarskiDominik** [comment]
Poprawione.
https://github.com/RybarskiDominik/GML-2021/releases/tag/1.5.2
