### ISSUE TITLE
Błędne oznaczenie wersji programu w instalatorze 1.6.0

### ISSUE THREAD

**Issue by Rzezimioszek** [RybarskiDominik/GML-2021#19]
Instalator dla wersji 1.6.0 sugeruje, że instalujemy wersję 1.5.5

![image](https://github.com/user-attachments/assets/bf405487-0870-49ed-96b6-ded5ff968f08)

**Comment by RybarskiDominik** [comment]
Tak jest to błąd samego instalatora, w ustawieniach jest możliwość sprawdzenia zainstalowanej wersji.
Jak poprawię rzeczy z twojego drugiego tematu to wstawię wersję poprawną.

**Comment by RybarskiDominik** [comment]
Rozwiązane.
https://github.com/RybarskiDominik/GML-2021/releases/tag/1.6.1
