### ISSUE TITLE
Maksymalizacja okna programu i błędne pole pesel oraz inne

### ISSUE THREAD

**Issue by Rzezimioszek** [RybarskiDominik/GML-2021#20]
Maksymalizacja okna programu nie zwiększa wysokości tabeli z danymi do wysokości całego okna.

![image](https://github.com/user-attachments/assets/32d105d7-4fb8-467d-b3ce-7fd0abc6d2c4)

W polu Pesel w przypadku podmiotu będącego isntytucją wyświetla się Regon, brak jest również informacjo o skróconej nazwie w sytuacji gdy jest ona różna od nazwy pełnej.

Adres powinien być rozdzielany jakimś znakiem np. "96-314 Baranów; Armi krajowej 87", a w przypadku braku ulicy "96-314 Baranów;  Baranów 87" ułatwiłoby to rozdzielenie tego na dwie kolumny w innych programach np. excel, access. Wgl wydaje mi się że ulica, a dopiero potem poczta wygląda naturalniej jako adres "Armi krajowej 87; 96-314 Baranów".

Pliki, które testowałem poprawnie wczytują arkusz Dane osobowe, ale z działkami jest problem. Część plików wyświetla działki w tabeli działki, lecz nie grafikę w mapie, a część w drugą stronę pokazuje grafikę, ale tabela działki jest pusta.

Brakuje mi gdzieś w nagłówku lub na jakiejś etykiecie nazwy wczytanego pliku, przy pracy na większej ilości plików i powiatów jest to przydatne, aby wiedzieć co się ma wczytane, gdy na przykład było się zajętym czymś innym i wraca się do programu po czasie, aby mieć pewność na czym pracuje musze wczytać to jeszcze raz.

Ogólnie spoko program podoba mi się idea takiego trochę C-SWDE, ale ogólnie dostępnego. Jeszcze jakbyś kiedyś zrobił do tego eksport wypisów na podstawie szablonów to myślę, że byłoby to mocne. Sam też pracuje nad czymś do gmli z egib 2021, ale bardziej celuje w suchy eksporter, niż narzędzie do pracy na pliku. Będę korzystał twojego programu równolegle z innymi, więc pewnie wyłapie jeszcze jakieś nieścisłości, ale i tak odwaliłeś kawał fajnej roboty.

**Comment by RybarskiDominik** [comment]
W folderze gdzie jest zainstalowany program, jest plik log.log i tam znajduje się dziennik błędów.
Najlepiej włączyć na nowo program aby wyczyścił on stary dziennik, wywołać błąd w programie i zobaczyć co jest w pliku.

**Comment by RybarskiDominik** [comment]
Nowa wersja programu.
https://github.com/RybarskiDominik/GML-2021/releases/tag/1.6.1
